export const nbaEnToHe = {
  "Atlanta Hawks": "אטלנטה הוקס",
  "Boston Celtics": "בוסטון סלטיקס",
  "Brooklyn Nets": "ברוקלין נטס",
  "Charlotte Hornets": "שארלוט הורנטס",
  "Chicago Bulls": "שיקגו בולס",
  "Cleveland Cavaliers": "קליבלנד קאבלירס",
  "Dallas Mavericks": "דאלאס מאבריקס",
  "Denver Nuggets": "דנבר נאגטס",
  "Detroit Pistons": "דטרויט פיסטונס",
  "Golden State Warriors": "גולדן סטייט ווריורס",
  "Houston Rockets": "יוסטון רוקטס",
  "Indiana Pacers": "אינדיאנה פייסרס",
  "LA Clippers": "לוס אנג'לס קליפרס",
  "Los Angeles Lakers": "לוס אנג'לס לייקרס",
  "Memphis Grizzlies": "ממפיס גריזליס",
  "Miami Heat": "מיאמי היט",
  "Milwaukee Bucks": "מילווקי באקס",
  "Minnesota Timberwolves": "מינסוטה טימברוולבס",
  "New Orleans Pelicans": "ניו אורלינס פליקנס",
  "New York Knicks": "ניו יורק ניקס",
  "Oklahoma City Thunder": "אוקלהומה סיטי ת'אנדר",
  "Orlando Magic": "אורלנדו מג'יק",
  "Philadelphia 76ers": "פילדלפיה 76'רס",
  "Phoenix Suns": "פיניקס סאנס",
  "Portland Trail Blazers": "פורטלנד טרייל בלייזרס",
  "Sacramento Kings": "סקרמנטו קינגס",
  "San Antonio Spurs": "סן אנטוניו ספרס",
  "Toronto Raptors": "טורונטו ראפטורס",
  "Utah Jazz": "יוטה ג'אז",
  "Washington Wizards": "וושינגטון ויזארדס"
};

export const nbaHeAltNames = {
  "Philadelphia 76ers": ["פילדלפיה סיקסרס", "פילדלפיה 76'רס"],
};
// Short Hebrew team nicknames, for compact score rows
export const nbaShortHe = {
  "Atlanta Hawks": "הוקס",
  "Boston Celtics": "סלטיקס",
  "Brooklyn Nets": "נטס",
  "Charlotte Hornets": "הורנטס",
  "Chicago Bulls": "בולס",
  "Cleveland Cavaliers": "קאבלירס",
  "Dallas Mavericks": "מאבריקס",
  "Denver Nuggets": "נאגטס",
  "Detroit Pistons": "פיסטונס",
  "Golden State Warriors": "ווריורס",
  "Houston Rockets": "רוקטס",
  "Indiana Pacers": "פייסרס",
  "LA Clippers": "קליפרס",
  "Los Angeles Lakers": "לייקרס",
  "Memphis Grizzlies": "גריזליס",
  "Miami Heat": "היט",
  "Milwaukee Bucks": "באקס",
  "Minnesota Timberwolves": "טימברוולבס",
  "New Orleans Pelicans": "פליקנס",
  "New York Knicks": "ניקס",
  "Oklahoma City Thunder": "ת'אנדר",
  "Orlando Magic": "מג'יק",
  "Philadelphia 76ers": "76'רס",
  "Phoenix Suns": "סאנס",
  "Portland Trail Blazers": "בלייזרס",
  "Sacramento Kings": "קינגס",
  "San Antonio Spurs": "ספרס",
  "Toronto Raptors": "ראפטורס",
  "Utah Jazz": "ג'אז",
  "Washington Wizards": "ויזארדס"
};
