export const nbaEnToHe = {
  "Atlanta Hawks": "אטלנטה הוקס",
  "Boston Celtics": "בוסטון סלטיקס",
  "Brooklyn Nets": "ברוקלין נטס",
  "Charlotte Hornets": "שארלוט הורנטס",
  "Chicago Bulls": "שיקגו בולס",
  "Cleveland Cavaliers": "קליבלנד קאבלירס",
  "Dallas Mavericks": "דאלאס מאבריקס",
  "Denver Nuggets": "דנבר נאגטס",
  "Detroit Pistons": "דטרויט פיסטונס",
  "Golden State Warriors": "גולדן סטייט ווריורס",
  "Houston Rockets": "יוסטון רוקטס",
  "Indiana Pacers": "אינדיאנה פייסרס",
  "LA Clippers": "לוס אנג'לס קליפרס",
  "Los Angeles Lakers": "לוס אנג'לס לייקרס",
  "Memphis Grizzlies": "ממפיס גריזליס",
  "Miami Heat": "מיאמי היט",
  "Milwaukee Bucks": "מילווקי באקס",
  "Minnesota Timberwolves": "מינסוטה טימברוולבס",
  "New Orleans Pelicans": "ניו אורלינס פליקנס",
  "New York Knicks": "ניו יורק ניקס",
  "Oklahoma City Thunder": "אוקלהומה סיטי ת'אנדר",
  "Orlando Magic": "אורלנדו מג'יק",
  "Philadelphia 76ers": "פילדלפיה 76'רס",
  "Phoenix Suns": "פיניקס סאנס",
  "Portland Trail Blazers": "פורטלנד טרייל בלייזרס",
  "Sacramento Kings": "סקרמנטו קינגס",
  "San Antonio Spurs": "סן אנטוניו ספרס",
  "Toronto Raptors": "טורונטו ראפטורס",
  "Utah Jazz": "יוטה ג'אז",
  "Washington Wizards": "וושינגטון ויזארדס"
};